### ISSUE TITLE
File və qovluq strukturu.

### ISSUE THREAD

**Issue by EldanizAkbar** [feritkerimli/PragmatechFoundationProject#1]
Zəhmət olmasa layihəndə ki HTML fayllarını bir qovluğa yığ.

**Comment by feritkerimli** [comment]
Elə elədim ilk olaraq amma şəkillər gorsenmedi, kodlar işləmədi və s. problemlər oldu deyə belə elədim.

**Comment by feritkerimli** [comment]
Ən qısa müddətdə düzəltməyə calisacam

**Comment by feritkerimli** [comment]
Issue hell edildi
