### ISSUE TITLE
Layihə haqqında məlumat.

### ISSUE THREAD

**Issue by EldanizAkbar** [feritkerimli/PragmatechFoundationProject#2]
Zəhmət olmasa layihə haqqındə məlumatı readme faylı yaradıb ora yerləşdir.

**Comment by feritkerimli** [comment]
Baş uste. təşəkkürlər

1 fev 2021, B.E. 15:59 tarixində Eldaniz Akbarzada <notifications@github.com>
yazdı:

**Comment by feritkerimli** [comment]
Fayl yerlesdirildi
